# Generated by Django 5.2.6 on 2025-09-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepagegalleryimage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='cta_external_url',
        ),
        migrations.AddField(
            model_name='homepage',
            name='youtube_url',
            field=models.URLField(blank=True, default='https://www.youtube.com', null=True),
        ),
    ]
